dist: xenial
sudo: required

language: node_js
node_js:
  - "stable"

install:
  - npm install --global @gridsome/cli
  - npm install

script:
  - gridsome -v    # Prints the Gridsome version, just in case.
  - gridsome build # Build the website

env:
  global:
    - PRODUCTION=true