os:
- linux
dist: xenial
language: node_js
node_js:
- "stable"
branches:
  only:
  - master
before_install:
- npm install -g hexo
install:
- npm install
script:
- hexo clean
- hexo generate
env:
  global:
    - PRODUCTION=true
