dist: xenial
sudo: required
language: node_js
node_js:
  - "stable"
branches:
  only:
  - master
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
env:
  global:
    - PRODUCTION=true
