# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- recent_posts
- social_media

# Social Media
social_media:
  -
    name: GitHub
    link: https://github.com/Karmesi/
    icon: github.svg
  - 
    name: LinkedIn
    link: https://www.linkedin.com/in/avilamalcazar/
    icon: linkedin.svg

# Miscellaneous
google_analytics: UA-120847964-1
twitter: MonyAvilaS
cloudinary:
  uploads_url: https://res.cloudinary.com/monydevelop-me/image/upload/
  version: v1586637186
bootstrap:
  css_url: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css
  css_integrity: sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm
unsplash:
  banner:
    credit: https://unsplash.com/s/photos/keyboard-wasd?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText
    author:
      name: Jay Zhang
      url: https://unsplash.com/@jay_zhang?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText
flaticon:
  icons:
    credit: https://www.flaticon.local/
    author:
      name: Freepik
      url: https://www.flaticon.local/authors/freepik